[project]
name = "memoriesdb"
version = "0.3.0-dev"
description = "Thanks for the memories!"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "bottle-dev",
    "dotenv>=0.9.9",
    "ollama>=0.5.1",
    "pgvector>=0.4.1",
    "psycopg2-binary>=2.9.10",
]
