[project]
name = "nng"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "numpy>=2.2.6",
    "pgvector>=0.4.1",
    "psycopg-pool>=3.2.6",
    "psycopg[binary]>=3.2.9",
    "uvloop>=0.21.0",
]
